// AUTO-GENERATED BY UpdateMultiplayerVersion.ps1 - DO NOT MODIFY
#if UNITY_STANDALONE || UNITY_ANDROID || UNITY_GAMECORE || MICROSOFT_GAME_CORE || UNITY_SWITCH || UNITY_PS4 || UNITY_PS5
namespace PlayFab.Multiplayer
{
    internal static class Version
    {
        public static readonly string MultiplayerNativeVersion = "{1.7.9}PlayFab.Multiplayer.Unity.Release.(Win10-GDK)_2503.18001";
        public static readonly string MultiplayerUnityVersion = "{1.7.9.0-main.0}PlayFab.Multiplayer.Unity.Release.(Win10-GDK)_2503.18001";
    }
}
#endif
